export enum ErrorTypes {
    FORBIDDEN = "FORBIDDEN",
    UNAUTHENTICATED = "UNAUTHENTICATED",
    NOT_FOUND = "NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    GRAPHQL_VALIDATION_FAILED = "GRAPHQL_VALIDATION_FAILED",
    GRAPHQL_PARSE_FAILED = "GRAPHQL_PARSE_FAILED",
    BAD_USER_INPUT = "BAD_USER_INPUT",
}
